INSERT INTO okresy_linking(nazev, link) VALUES('Praha', 'http://linked.opendata.cz/resource/county/ab');
INSERT INTO okresy_linking(nazev, link) VALUES('Beroun', 'http://linked.opendata.cz/resource/county/be');
INSERT INTO okresy_linking(nazev, link) VALUES('Blansko', 'http://linked.opendata.cz/resource/county/bk');
INSERT INTO okresy_linking(nazev, link) VALUES('Brno město', 'http://linked.opendata.cz/resource/county/bm');
INSERT INTO okresy_linking(nazev, link) VALUES('Benešov', 'http://linked.opendata.cz/resource/county/bn');
INSERT INTO okresy_linking(nazev, link) VALUES('Brno venkov', 'http://linked.opendata.cz/resource/county/bo');
INSERT INTO okresy_linking(nazev, link) VALUES('Bruntál', 'http://linked.opendata.cz/resource/county/br');
INSERT INTO okresy_linking(nazev, link) VALUES('Břeclav', 'http://linked.opendata.cz/resource/county/bv');
INSERT INTO okresy_linking(nazev, link) VALUES('České Budějovice', 'http://linked.opendata.cz/resource/county/cb');
INSERT INTO okresy_linking(nazev, link) VALUES('Cheb', 'http://linked.opendata.cz/resource/county/ch');
INSERT INTO okresy_linking(nazev, link) VALUES('Český Krumlov', 'http://linked.opendata.cz/resource/county/ck');
INSERT INTO okresy_linking(nazev, link) VALUES('Česká Lípa', 'http://linked.opendata.cz/resource/county/cl');
INSERT INTO okresy_linking(nazev, link) VALUES('Chrudim', 'http://linked.opendata.cz/resource/county/cr');
INSERT INTO okresy_linking(nazev, link) VALUES('Chomutov', 'http://linked.opendata.cz/resource/county/cv');
INSERT INTO okresy_linking(nazev, link) VALUES('Děčín', 'http://linked.opendata.cz/resource/county/dc');
INSERT INTO okresy_linking(nazev, link) VALUES('Domažlice', 'http://linked.opendata.cz/resource/county/do');
INSERT INTO okresy_linking(nazev, link) VALUES('Frýdek-Místek', 'http://linked.opendata.cz/resource/county/fm');
INSERT INTO okresy_linking(nazev, link) VALUES('Havlíčkův Brod', 'http://linked.opendata.cz/resource/county/hb');
INSERT INTO okresy_linking(nazev, link) VALUES('Hradec Králové', 'http://linked.opendata.cz/resource/county/hk');
INSERT INTO okresy_linking(nazev, link) VALUES('Hodonín', 'http://linked.opendata.cz/resource/county/ho');
INSERT INTO okresy_linking(nazev, link) VALUES('Jičín', 'http://linked.opendata.cz/resource/county/jc');
INSERT INTO okresy_linking(nazev, link) VALUES('Jeseník', 'http://linked.opendata.cz/resource/county/je');
INSERT INTO okresy_linking(nazev, link) VALUES('Jindřichův Hradec', 'http://linked.opendata.cz/resource/county/jh');
INSERT INTO okresy_linking(nazev, link) VALUES('Jihlava', 'http://linked.opendata.cz/resource/county/ji');
INSERT INTO okresy_linking(nazev, link) VALUES('Jablonec nad Nisou', 'http://linked.opendata.cz/resource/county/jn');
INSERT INTO okresy_linking(nazev, link) VALUES('Kutná Hora', 'http://linked.opendata.cz/resource/county/kh');
INSERT INTO okresy_linking(nazev, link) VALUES('Karviná', 'http://linked.opendata.cz/resource/county/ki');
INSERT INTO okresy_linking(nazev, link) VALUES('Kladno', 'http://linked.opendata.cz/resource/county/kl');
INSERT INTO okresy_linking(nazev, link) VALUES('Kroměříž', 'http://linked.opendata.cz/resource/county/km');
INSERT INTO okresy_linking(nazev, link) VALUES('Kolín', 'http://linked.opendata.cz/resource/county/ko');
INSERT INTO okresy_linking(nazev, link) VALUES('Klatovy', 'http://linked.opendata.cz/resource/county/kt');
INSERT INTO okresy_linking(nazev, link) VALUES('Karlovy Vary', 'http://linked.opendata.cz/resource/county/kv');
INSERT INTO okresy_linking(nazev, link) VALUES('Liberec', 'http://linked.opendata.cz/resource/county/lb');
INSERT INTO okresy_linking(nazev, link) VALUES('Louny', 'http://linked.opendata.cz/resource/county/ln');
INSERT INTO okresy_linking(nazev, link) VALUES('Litoměřice', 'http://linked.opendata.cz/resource/county/lt');
INSERT INTO okresy_linking(nazev, link) VALUES('Mladá Boleslav', 'http://linked.opendata.cz/resource/county/mb');
INSERT INTO okresy_linking(nazev, link) VALUES('Mělník', 'http://linked.opendata.cz/resource/county/me');
INSERT INTO okresy_linking(nazev, link) VALUES('Most', 'http://linked.opendata.cz/resource/county/mo');
INSERT INTO okresy_linking(nazev, link) VALUES('Náchod', 'http://linked.opendata.cz/resource/county/na');
INSERT INTO okresy_linking(nazev, link) VALUES('Nymburk', 'http://linked.opendata.cz/resource/county/nb');
INSERT INTO okresy_linking(nazev, link) VALUES('Nový Jičín', 'http://linked.opendata.cz/resource/county/nj');
INSERT INTO okresy_linking(nazev, link) VALUES('Olomouc', 'http://linked.opendata.cz/resource/county/ol');
INSERT INTO okresy_linking(nazev, link) VALUES('Opava', 'http://linked.opendata.cz/resource/county/op');
INSERT INTO okresy_linking(nazev, link) VALUES('Ostrava', 'http://linked.opendata.cz/resource/county/ov');
INSERT INTO okresy_linking(nazev, link) VALUES('Příbram', 'http://linked.opendata.cz/resource/county/pb');
INSERT INTO okresy_linking(nazev, link) VALUES('Pelhřimov', 'http://linked.opendata.cz/resource/county/pe');
INSERT INTO okresy_linking(nazev, link) VALUES('Praha východ', 'http://linked.opendata.cz/resource/county/ph');
INSERT INTO okresy_linking(nazev, link) VALUES('Písek', 'http://linked.opendata.cz/resource/county/pi');
INSERT INTO okresy_linking(nazev, link) VALUES('Plzeň jih', 'http://linked.opendata.cz/resource/county/pj');
INSERT INTO okresy_linking(nazev, link) VALUES('Plzeň město', 'http://linked.opendata.cz/resource/county/pm');
INSERT INTO okresy_linking(nazev, link) VALUES('Přerov', 'http://linked.opendata.cz/resource/county/pr');
INSERT INTO okresy_linking(nazev, link) VALUES('Plzeň sever', 'http://linked.opendata.cz/resource/county/ps');
INSERT INTO okresy_linking(nazev, link) VALUES('Prachatice', 'http://linked.opendata.cz/resource/county/pt');
INSERT INTO okresy_linking(nazev, link) VALUES('Pardubice', 'http://linked.opendata.cz/resource/county/pu');
INSERT INTO okresy_linking(nazev, link) VALUES('Prostějov', 'http://linked.opendata.cz/resource/county/pv');
INSERT INTO okresy_linking(nazev, link) VALUES('Praha západ', 'http://linked.opendata.cz/resource/county/pz');
INSERT INTO okresy_linking(nazev, link) VALUES('Rakovník', 'http://linked.opendata.cz/resource/county/ra');
INSERT INTO okresy_linking(nazev, link) VALUES('Rychnov nad Kněžnou', 'http://linked.opendata.cz/resource/county/rk');
INSERT INTO okresy_linking(nazev, link) VALUES('Rokycany', 'http://linked.opendata.cz/resource/county/ro');
INSERT INTO okresy_linking(nazev, link) VALUES('Semily', 'http://linked.opendata.cz/resource/county/sm');
INSERT INTO okresy_linking(nazev, link) VALUES('Sokolov', 'http://linked.opendata.cz/resource/county/so');
INSERT INTO okresy_linking(nazev, link) VALUES('Strakonice', 'http://linked.opendata.cz/resource/county/st');
INSERT INTO okresy_linking(nazev, link) VALUES('Šumperk', 'http://linked.opendata.cz/resource/county/su');
INSERT INTO okresy_linking(nazev, link) VALUES('Svitavy', 'http://linked.opendata.cz/resource/county/sy');
INSERT INTO okresy_linking(nazev, link) VALUES('Tábor', 'http://linked.opendata.cz/resource/county/ta');
INSERT INTO okresy_linking(nazev, link) VALUES('Tachov', 'http://linked.opendata.cz/resource/county/tc');
INSERT INTO okresy_linking(nazev, link) VALUES('Teplice', 'http://linked.opendata.cz/resource/county/tp');
INSERT INTO okresy_linking(nazev, link) VALUES('Třebíč', 'http://linked.opendata.cz/resource/county/tr');
INSERT INTO okresy_linking(nazev, link) VALUES('Trutnov', 'http://linked.opendata.cz/resource/county/tu');
INSERT INTO okresy_linking(nazev, link) VALUES('Uherské Hradiště', 'http://linked.opendata.cz/resource/county/uh');
INSERT INTO okresy_linking(nazev, link) VALUES('Ústí nad Labem', 'http://linked.opendata.cz/resource/county/ul');
INSERT INTO okresy_linking(nazev, link) VALUES('Ústí nad Orlicí', 'http://linked.opendata.cz/resource/county/uo');
INSERT INTO okresy_linking(nazev, link) VALUES('Vsetín', 'http://linked.opendata.cz/resource/county/vs');
INSERT INTO okresy_linking(nazev, link) VALUES('Vyškov', 'http://linked.opendata.cz/resource/county/vy');
INSERT INTO okresy_linking(nazev, link) VALUES('Zlín', 'http://linked.opendata.cz/resource/county/zl');
INSERT INTO okresy_linking(nazev, link) VALUES('Znojmo', 'http://linked.opendata.cz/resource/county/zn');
INSERT INTO okresy_linking(nazev, link) VALUES('Žďár nad Sázavou', 'http://linked.opendata.cz/resource/county/zr');
