UNION { ?country a <http://schema.org/Country>; <http://dbpedia.org/ontology/capital> ?capital . OPTIONAL {?country dbpprop:yearEnd ?yearEnd } FILTER(!bound(?yearEnd)) . ?country rdfs:label ?label . FILTER(REGEX(?label, "Sri")) FILTER(REGEX(?label, "Lanka")) BIND(<http://linked.opendata.cz/ontology/crimestatistics/code/stat#603> as ?stat) }
UNION { ?country a <http://schema.org/Country>; <http://dbpedia.org/ontology/capital> ?capital . OPTIONAL {?country dbpprop:yearEnd ?yearEnd } FILTER(!bound(?yearEnd)) . ?country rdfs:label ?label . FILTER(REGEX(?label, "Central")) FILTER(REGEX(?label, "African")) BIND(<http://linked.opendata.cz/ontology/crimestatistics/code/stat#675> as ?stat) }
UNION { ?country a <http://schema.org/Country>; <http://dbpedia.org/ontology/capital> ?capital . OPTIONAL {?country dbpprop:yearEnd ?yearEnd } FILTER(!bound(?yearEnd)) . ?country rdfs:label ?label . FILTER(REGEX(?label, "Sudan")) BIND(<http://linked.opendata.cz/ontology/crimestatistics/code/stat#676> as ?stat) }
UNION { ?country a <http://schema.org/Country>; <http://dbpedia.org/ontology/capital> ?capital . OPTIONAL {?country dbpprop:yearEnd ?yearEnd } FILTER(!bound(?yearEnd)) . ?country rdfs:label ?label . FILTER(REGEX(?label, "Suriname")) BIND(<http://linked.opendata.cz/ontology/crimestatistics/code/stat#705> as ?stat) }
UNION { ?country a <http://schema.org/Country>; <http://dbpedia.org/ontology/capital> ?capital . OPTIONAL {?country dbpprop:yearEnd ?yearEnd } FILTER(!bound(?yearEnd)) . ?country rdfs:label ?label . FILTER(REGEX(?label, "Svalbard")) FILTER(REGEX(?label, "Jan")) FILTER(REGEX(?label, "Mayen")) BIND(<http://linked.opendata.cz/ontology/crimestatistics/code/stat#707> as ?stat) }
UNION { ?country a <http://schema.org/Country>; <http://dbpedia.org/ontology/capital> ?capital . OPTIONAL {?country dbpprop:yearEnd ?yearEnd } FILTER(!bound(?yearEnd)) . ?country rdfs:label ?label . FILTER(REGEX(?label, "Saint")) FILTER(REGEX(?label, "Helena")) BIND(<http://linked.opendata.cz/ontology/crimestatistics/code/stat#708> as ?stat) }
UNION { ?country a <http://schema.org/Country>; <http://dbpedia.org/ontology/capital> ?capital . OPTIONAL {?country dbpprop:yearEnd ?yearEnd } FILTER(!bound(?yearEnd)) . ?country rdfs:label ?label . FILTER(REGEX(?label, "Saint")) FILTER(REGEX(?label, "Lucia")) BIND(<http://linked.opendata.cz/ontology/crimestatistics/code/stat#709> as ?stat) }
UNION { ?country a <http://schema.org/Country>; <http://dbpedia.org/ontology/capital> ?capital . OPTIONAL {?country dbpprop:yearEnd ?yearEnd } FILTER(!bound(?yearEnd)) . ?country rdfs:label ?label . FILTER(REGEX(?label, "Saint")) FILTER(REGEX(?label, "Kitts")) FILTER(REGEX(?label, "Nevis")) BIND(<http://linked.opendata.cz/ontology/crimestatistics/code/stat#710> as ?stat) }
UNION { ?country a <http://schema.org/Country>; <http://dbpedia.org/ontology/capital> ?capital . OPTIONAL {?country dbpprop:yearEnd ?yearEnd } FILTER(!bound(?yearEnd)) . ?country rdfs:label ?label . FILTER(REGEX(?label, "Vatican")) BIND(<http://linked.opendata.cz/ontology/crimestatistics/code/stat#711> as ?stat) }
UNION { ?country a <http://schema.org/Country>; <http://dbpedia.org/ontology/capital> ?capital . OPTIONAL {?country dbpprop:yearEnd ?yearEnd } FILTER(!bound(?yearEnd)) . ?country rdfs:label ?label . FILTER(REGEX(?label, "Sao")) FILTER(REGEX(?label, "Tomé")) FILTER(REGEX(?label, "Príncipe")) BIND(<http://linked.opendata.cz/ontology/crimestatistics/code/stat#712> as ?stat) }
UNION { ?country a <http://schema.org/Country>; <http://dbpedia.org/ontology/capital> ?capital . OPTIONAL {?country dbpprop:yearEnd ?yearEnd } FILTER(!bound(?yearEnd)) . ?country rdfs:label ?label . FILTER(REGEX(?label, "Saint")) FILTER(REGEX(?label, "Vincent")) FILTER(REGEX(?label, "Grenadines")) BIND(<http://linked.opendata.cz/ontology/crimestatistics/code/stat#706> as ?stat) }
