UNION { ?country a <http://schema.org/Country>; <http://dbpedia.org/ontology/capital> ?capital; OPTIONAL {?country dbpprop:yearEnd ?yearEnd; dbprop:dissolutionYear ?dissYear; dbprop:dissolutionDate ?dissDate; dbprop:dateEnd ?dateEnd .} FILTER (!bound(?yearEnd)) FILTER (!bound(?dissYear)) FILTER (!bound(?dissDate)) FILTER (!bound(?dateEnd)) rdfs:label ?label . FILTER(REGEX(?label, "")) BIND(<http://linked.opendata.cz/ontology/crimestatistics/code/stat#﻿010 Czech Republic> as ?stat) }
UNION { ?country a <http://schema.org/Country>; <http://dbpedia.org/ontology/capital> ?capital; OPTIONAL {?country dbpprop:yearEnd ?yearEnd; dbprop:dissolutionYear ?dissYear; dbprop:dissolutionDate ?dissDate; dbprop:dateEnd ?dateEnd .} FILTER (!bound(?yearEnd)) FILTER (!bound(?dissYear)) FILTER (!bound(?dissDate)) FILTER (!bound(?dateEnd)) rdfs:label ?label . FILTER(REGEX(?label, "Slovak Rep")) BIND(<http://linked.opendata.cz/ontology/crimestatistics/code/stat#050> as ?stat) }
UNION { ?country a <http://schema.org/Country>; <http://dbpedia.org/ontology/capital> ?capital; OPTIONAL {?country dbpprop:yearEnd ?yearEnd; dbprop:dissolutionYear ?dissYear; dbprop:dissolutionDate ?dissDate; dbprop:dateEnd ?dateEnd .} FILTER (!bound(?yearEnd)) FILTER (!bound(?dissYear)) FILTER (!bound(?dissDate)) FILTER (!bound(?dateEnd)) rdfs:label ?label . FILTER(REGEX(?label, "Russia")) BIND(<http://linked.opendata.cz/ontology/crimestatistics/code/stat#101> as ?stat) }
UNION { ?country a <http://schema.org/Country>; <http://dbpedia.org/ontology/capital> ?capital; OPTIONAL {?country dbpprop:yearEnd ?yearEnd; dbprop:dissolutionYear ?dissYear; dbprop:dissolutionDate ?dissDate; dbprop:dateEnd ?dateEnd .} FILTER (!bound(?yearEnd)) FILTER (!bound(?dissYear)) FILTER (!bound(?dissDate)) FILTER (!bound(?dateEnd)) rdfs:label ?label . FILTER(REGEX(?label, "Tajikistan")) BIND(<http://linked.opendata.cz/ontology/crimestatistics/code/stat#102> as ?stat) }
UNION { ?country a <http://schema.org/Country>; <http://dbpedia.org/ontology/capital> ?capital; OPTIONAL {?country dbpprop:yearEnd ?yearEnd; dbprop:dissolutionYear ?dissYear; dbprop:dissolutionDate ?dissDate; dbprop:dateEnd ?dateEnd .} FILTER (!bound(?yearEnd)) FILTER (!bound(?dissYear)) FILTER (!bound(?dissDate)) FILTER (!bound(?dateEnd)) rdfs:label ?label . FILTER(REGEX(?label, "Turkmenist")) BIND(<http://linked.opendata.cz/ontology/crimestatistics/code/stat#103> as ?stat) }
UNION { ?country a <http://schema.org/Country>; <http://dbpedia.org/ontology/capital> ?capital; OPTIONAL {?country dbpprop:yearEnd ?yearEnd; dbprop:dissolutionYear ?dissYear; dbprop:dissolutionDate ?dissDate; dbprop:dateEnd ?dateEnd .} FILTER (!bound(?yearEnd)) FILTER (!bound(?dissYear)) FILTER (!bound(?dissDate)) FILTER (!bound(?dateEnd)) rdfs:label ?label . FILTER(REGEX(?label, "Ukraine")) BIND(<http://linked.opendata.cz/ontology/crimestatistics/code/stat#104> as ?stat) }
UNION { ?country a <http://schema.org/Country>; <http://dbpedia.org/ontology/capital> ?capital; OPTIONAL {?country dbpprop:yearEnd ?yearEnd; dbprop:dissolutionYear ?dissYear; dbprop:dissolutionDate ?dissDate; dbprop:dateEnd ?dateEnd .} FILTER (!bound(?yearEnd)) FILTER (!bound(?dissYear)) FILTER (!bound(?dissDate)) FILTER (!bound(?dateEnd)) rdfs:label ?label . FILTER(REGEX(?label, "Uzbekistan")) BIND(<http://linked.opendata.cz/ontology/crimestatistics/code/stat#105> as ?stat) }
UNION { ?country a <http://schema.org/Country>; <http://dbpedia.org/ontology/capital> ?capital; OPTIONAL {?country dbpprop:yearEnd ?yearEnd; dbprop:dissolutionYear ?dissYear; dbprop:dissolutionDate ?dissDate; dbprop:dateEnd ?dateEnd .} FILTER (!bound(?yearEnd)) FILTER (!bound(?dissYear)) FILTER (!bound(?dissDate)) FILTER (!bound(?dateEnd)) rdfs:label ?label . FILTER(REGEX(?label, "Albania")) BIND(<http://linked.opendata.cz/ontology/crimestatistics/code/stat#110> as ?stat) }
UNION { ?country a <http://schema.org/Country>; <http://dbpedia.org/ontology/capital> ?capital; OPTIONAL {?country dbpprop:yearEnd ?yearEnd; dbprop:dissolutionYear ?dissYear; dbprop:dissolutionDate ?dissDate; dbprop:dateEnd ?dateEnd .} FILTER (!bound(?yearEnd)) FILTER (!bound(?dissYear)) FILTER (!bound(?dissDate)) FILTER (!bound(?dateEnd)) rdfs:label ?label . FILTER(REGEX(?label, "Bulgaria")) BIND(<http://linked.opendata.cz/ontology/crimestatistics/code/stat#120> as ?stat) }
UNION { ?country a <http://schema.org/Country>; <http://dbpedia.org/ontology/capital> ?capital; OPTIONAL {?country dbpprop:yearEnd ?yearEnd; dbprop:dissolutionYear ?dissYear; dbprop:dissolutionDate ?dissDate; dbprop:dateEnd ?dateEnd .} FILTER (!bound(?yearEnd)) FILTER (!bound(?dissYear)) FILTER (!bound(?dissDate)) FILTER (!bound(?dateEnd)) rdfs:label ?label . FILTER(REGEX(?label, "Hungary")) BIND(<http://linked.opendata.cz/ontology/crimestatistics/code/stat#130> as ?stat) }
UNION { ?country a <http://schema.org/Country>; <http://dbpedia.org/ontology/capital> ?capital; OPTIONAL {?country dbpprop:yearEnd ?yearEnd; dbprop:dissolutionYear ?dissYear; dbprop:dissolutionDate ?dissDate; dbprop:dateEnd ?dateEnd .} FILTER (!bound(?yearEnd)) FILTER (!bound(?dissYear)) FILTER (!bound(?dissDate)) FILTER (!bound(?dateEnd)) rdfs:label ?label . FILTER(REGEX(?label, "Poland")) BIND(<http://linked.opendata.cz/ontology/crimestatistics/code/stat#150> as ?stat) }
UNION { ?country a <http://schema.org/Country>; <http://dbpedia.org/ontology/capital> ?capital; OPTIONAL {?country dbpprop:yearEnd ?yearEnd; dbprop:dissolutionYear ?dissYear; dbprop:dissolutionDate ?dissDate; dbprop:dateEnd ?dateEnd .} FILTER (!bound(?yearEnd)) FILTER (!bound(?dissYear)) FILTER (!bound(?dissDate)) FILTER (!bound(?dateEnd)) rdfs:label ?label . FILTER(REGEX(?label, "Romania")) BIND(<http://linked.opendata.cz/ontology/crimestatistics/code/stat#160> as ?stat) }
UNION { ?country a <http://schema.org/Country>; <http://dbpedia.org/ontology/capital> ?capital; OPTIONAL {?country dbpprop:yearEnd ?yearEnd; dbprop:dissolutionYear ?dissYear; dbprop:dissolutionDate ?dissDate; dbprop:dateEnd ?dateEnd .} FILTER (!bound(?yearEnd)) FILTER (!bound(?dissYear)) FILTER (!bound(?dissDate)) FILTER (!bound(?dateEnd)) rdfs:label ?label . FILTER(REGEX(?label, "Mongolia")) BIND(<http://linked.opendata.cz/ontology/crimestatistics/code/stat#180> as ?stat) }
