UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Benešov") BIND(crimestatistics-code-codelist-hash:0101 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Beroun") BIND(crimestatistics-code-codelist-hash:0102 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Blansko") BIND(crimestatistics-code-codelist-hash:0601 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Břeclav") BIND(crimestatistics-code-codelist-hash:0604 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Brno město") BIND(crimestatistics-code-codelist-hash:0602 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Brno venkov") BIND(crimestatistics-code-codelist-hash:0603 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Bruntál") BIND(crimestatistics-code-codelist-hash:0701 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Česká Lípa") BIND(crimestatistics-code-codelist-hash:0401 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "České Budějovice") BIND(crimestatistics-code-codelist-hash:0201 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Český Krumlov") BIND(crimestatistics-code-codelist-hash:0202 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Cheb") BIND(crimestatistics-code-codelist-hash:0302 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Chomutov") BIND(crimestatistics-code-codelist-hash:0403 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Chrudim") BIND(crimestatistics-code-codelist-hash:0503 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Děčín") BIND(crimestatistics-code-codelist-hash:0402 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Domažlice") BIND(crimestatistics-code-codelist-hash:0301 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Frýdek-Místek") BIND(crimestatistics-code-codelist-hash:0702 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Havlíčkův Brod") BIND(crimestatistics-code-codelist-hash:0501 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Hodonín") BIND(crimestatistics-code-codelist-hash:0606 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Hradec Králové") BIND(crimestatistics-code-codelist-hash:0502 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Jablonec nad Nisou") BIND(crimestatistics-code-codelist-hash:0404 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Jeseník") BIND(crimestatistics-code-codelist-hash:0711 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Jičín") BIND(crimestatistics-code-codelist-hash:0504 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Jihlava") BIND(crimestatistics-code-codelist-hash:0607 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Jindřichův Hradec") BIND(crimestatistics-code-codelist-hash:0203 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Karlovy Vary") BIND(crimestatistics-code-codelist-hash:0303 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Karviná") BIND(crimestatistics-code-codelist-hash:0703 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Kladno") BIND(crimestatistics-code-codelist-hash:0103 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Klatovy") BIND(crimestatistics-code-codelist-hash:0304 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Kolín") BIND(crimestatistics-code-codelist-hash:0104 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Kroměříž") BIND(crimestatistics-code-codelist-hash:0608 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Kutná Hora") BIND(crimestatistics-code-codelist-hash:0105 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Liberec") BIND(crimestatistics-code-codelist-hash:0405 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Litoměřice") BIND(crimestatistics-code-codelist-hash:0406 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Louny") BIND(crimestatistics-code-codelist-hash:0407 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Mělník") BIND(crimestatistics-code-codelist-hash:0106 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Mladá Boleslav") BIND(crimestatistics-code-codelist-hash:0107 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Most") BIND(crimestatistics-code-codelist-hash:0408 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Náchod") BIND(crimestatistics-code-codelist-hash:0505 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Nový Jičín") BIND(crimestatistics-code-codelist-hash:0704 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Nymburk") BIND(crimestatistics-code-codelist-hash:0108 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Olomouc") BIND(crimestatistics-code-codelist-hash:0705 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Opava") BIND(crimestatistics-code-codelist-hash:0706 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Ostrava") BIND(crimestatistics-code-codelist-hash:0707 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Pardubice") BIND(crimestatistics-code-codelist-hash:0506 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Pelhřimov") BIND(crimestatistics-code-codelist-hash:0204 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Písek") BIND(crimestatistics-code-codelist-hash:0205 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Plzeň město") BIND(crimestatistics-code-codelist-hash:0305 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Plzeň jih") BIND(crimestatistics-code-codelist-hash:0306 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Plzeň sever") BIND(crimestatistics-code-codelist-hash:0307 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Prachatice") BIND(crimestatistics-code-codelist-hash:0206 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Praha") BIND(crimestatistics-code-codelist-hash:0040 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Praha") BIND(crimestatistics-code-codelist-hash:0050 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Praha") BIND(crimestatistics-code-codelist-hash:0057 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Praha") BIND(crimestatistics-code-codelist-hash:0090 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Praha") BIND(crimestatistics-code-codelist-hash:0092 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Praha") BIND(crimestatistics-code-codelist-hash:0093 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Praha") BIND(crimestatistics-code-codelist-hash:0001 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Praha") BIND(crimestatistics-code-codelist-hash:0010 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Praha") BIND(crimestatistics-code-codelist-hash:0002 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Praha") BIND(crimestatistics-code-codelist-hash:0003 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Praha") BIND(crimestatistics-code-codelist-hash:0004 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Praha") BIND(crimestatistics-code-codelist-hash:0005 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Praha") BIND(crimestatistics-code-codelist-hash:0006 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Praha") BIND(crimestatistics-code-codelist-hash:0007 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Praha") BIND(crimestatistics-code-codelist-hash:0008 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Praha") BIND(crimestatistics-code-codelist-hash:0009 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Praha") BIND(crimestatistics-code-codelist-hash:0011 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Praha") BIND(crimestatistics-code-codelist-hash:0012 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Praha") BIND(crimestatistics-code-codelist-hash:0013 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Praha východ") BIND(crimestatistics-code-codelist-hash:0109 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Praha západ") BIND(crimestatistics-code-codelist-hash:0110 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Přerov") BIND(crimestatistics-code-codelist-hash:0708 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Příbram") BIND(crimestatistics-code-codelist-hash:0111 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Prostějov") BIND(crimestatistics-code-codelist-hash:0712 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Prostějov") BIND(crimestatistics-code-codelist-hash:0609 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Rakovník") BIND(crimestatistics-code-codelist-hash:0112 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Rokycany") BIND(crimestatistics-code-codelist-hash:0308 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Rychnov nad Kněžnou") BIND(crimestatistics-code-codelist-hash:0507 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Semily") BIND(crimestatistics-code-codelist-hash:0508 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Semily") BIND(crimestatistics-code-codelist-hash:0411 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Sokolov") BIND(crimestatistics-code-codelist-hash:0309 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Strakonice") BIND(crimestatistics-code-codelist-hash:0207 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Šumperk") BIND(crimestatistics-code-codelist-hash:0709 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Svitavy") BIND(crimestatistics-code-codelist-hash:0509 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Tábor") BIND(crimestatistics-code-codelist-hash:0208 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Tachov") BIND(crimestatistics-code-codelist-hash:0310 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Teplice") BIND(crimestatistics-code-codelist-hash:0409 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Třebíč") BIND(crimestatistics-code-codelist-hash:0610 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Trutnov") BIND(crimestatistics-code-codelist-hash:0510 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Uherské Hradiště") BIND(crimestatistics-code-codelist-hash:0611 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Ústí nad Labem") BIND(crimestatistics-code-codelist-hash:0410 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Ústí nad Orlicí") BIND(crimestatistics-code-codelist-hash:0511 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Vsetín") BIND(crimestatistics-code-codelist-hash:0615 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Vsetín") BIND(crimestatistics-code-codelist-hash:0710 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Vyškov") BIND(crimestatistics-code-codelist-hash:0612 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Žďár nad Sázavou") BIND(crimestatistics-code-codelist-hash:0614 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Žďár nad Sázavou") BIND(crimestatistics-code-codelist-hash:1614 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Zlín") BIND(crimestatistics-code-codelist-hash:0605 as ?kod) }
UNION { ?okres rdf:type cm:County . ?okres geonames:officialName ?name . FILTER(STR(?name) = "Znojmo") BIND(crimestatistics-code-codelist-hash:0613 as ?kod) }
